### ISSUE TITLE
SoftCursor is disappear on IMGUI of plugins  (need GUI.depth setting on SoftCursor)

### ISSUE THREAD

**Issue by vrvrl0ver** [Eusth/VRGIN#11]
First of all, thank you very much for your effort on enhancing this library.

I'm having a GUI (IMGUI) problem in my plugin (HoneySelect studio addon).
When I use Menu tool, and try to point my plugin's GUI object (IMGUI window/buttons/etc.), simulated mouse cursor is disappear when I points over the GUI  window.
It makes difficult to select items on GUI.

As I see the code in VRGIN.Visual.SoftCursor class, which uses IMGUI to draw the mouse cursor, I found that the GUI.depth is not specified in the code. So that SoftCursor may draw the mouse cursor before my plugins, and it was hide by my plugin's GUI.

I think I can workaround the problem by larger GUI.depth in my plugin. However, it is good if the SoftCursor uses very small depth (such like -1000 or int.MinValue + 1) that makes the SoftCursor draws the mouse cursor over all of the IMGUI elements.  

Could you please see this issue?

**Comment by Eusth** [comment]
Ah, I see. Didn't think about that when I rewrote the code for Rinkan.

I'll take a look at it. Alternatively, feel free to send a PR.

**Comment by vrvrl0ver** [comment]
Thank you for applying the proposed change. I noticed that you have added a commit for this.
