### ISSUE TITLE
how can see panorama img?

### ISSUE THREAD

**Issue by arthurOmanko** [Eusth/VRGIN#19]
how can see panorama img?
i took panorama img and sccessed.
but only it meaningless for normal viewer.
what viewer should i use?

**Comment by Eusth** [comment]
IIRC the snapshots use an equirectangular projection with a top-down layout.

I don't know of a viewer that works out of the box, but it's pretty simple.

Here's an example with Babylon.js:
https://www.babylonjs-playground.com/#14KRGG#236

Simply drag & drop your panorama.

**Comment by arthurOmanko** [comment]
tks very much reply.
ive solved.
because im forking your code, ill add some more functions (IK control etc.) later.
tks.
